export const STR = {
  en: {
    appTitle: 'Digital Pathshala',
    welcome: 'Welcome to Digital Pathshala',
    // Navbar
    nav_home: 'Home',
    nav_about: 'About',
    nav_student: 'Student',
    nav_teacher: 'Teacher',
    nav_admin: 'Admin',
    nav_downloads: 'Downloads',
    nav_assignments: 'Assignments',
    nav_attendance: 'Attendance',
    nav_announcements: 'Announcements',
    nav_login: 'Login',
    nav_logout: 'Logout',
    nav_dark: 'Dark',
    nav_light: 'Light',
    // Home
    home_problem: 'Problem Statement',
    home_expected: 'Expected Outcomes',
    home_point_offline: 'Offline-capable lessons',
    home_point_locale: 'Local language content',
    home_point_dash: 'Teacher dashboards',
    // Student
    student_title: 'Student Dashboard',
    student_minutes: 'minutes',
    student_download: 'Download',
    student_start: 'Start',
    student_status: 'Status',
    student_offline: 'Offline',
    student_online: 'Online',
    student_progress: 'My Progress',
    // Teacher
    teacher_title: 'Teacher Dashboard',
    teacher_upload_label: 'Upload Resource',
    teacher_upload_btn: 'Upload',
    // Admin
    admin_title: 'Admin Dashboard',
    admin_add_student: 'Add Student',
    admin_add_btn: 'Add',
    admin_manage: 'Manage roles and export data (placeholders)',
    // About
    about_title: 'About',
    about_desc:
      'This platform helps bridge the digital divide in rural Nabha by providing offline lessons, multi-language content, and teacher/admin tools.',
  },
  hi: {
    appTitle: 'डिजिटल पाठशाला',
    welcome: 'डिजिटल पाठशाला में आपका स्वागत है',
    nav_home: 'होम',
    nav_about: 'परिचय',
    nav_student: 'विद्यार्थी',
    nav_teacher: 'अध्यापक',
    nav_admin: 'प्रशासन',
    nav_downloads: 'डाउनलोड',
    nav_assignments: 'असाइनमेंट',
    nav_attendance: 'हाज़िरी',
    nav_announcements: 'घोषणाएँ',
    nav_login: 'लॉगिन',
    nav_logout: 'लॉगआउट',
    nav_dark: 'डार्क',
    nav_light: 'लाइट',
    home_problem: 'समस्या विवरण',
    home_expected: 'अपेक्षित परिणाम',
    home_point_offline: 'ऑफलाइन पाठ',
    home_point_locale: 'स्थानीय भाषा सामग्री',
    home_point_dash: 'शिक्षक डैशबोर्ड',
    student_title: 'विद्यार्थी डैशबोर्ड',
    student_minutes: 'मिनट',
    student_download: 'डाउनलोड',
    student_start: 'शुरू करें',
    student_status: 'स्थिति',
    student_offline: 'ऑफलाइन',
    student_online: 'ऑनलाइन',
    student_progress: 'मेरी प्रगति',
    teacher_title: 'अध्यापक डैशबोर्ड',
    teacher_upload_label: 'संसाधन अपलोड करें',
    teacher_upload_btn: 'अपलोड',
    admin_title: 'प्रशासन डैशबोर्ड',
    admin_add_student: 'छात्र जोड़ें',
    admin_add_btn: 'जोड़ें',
    admin_manage: 'भूमिकाएँ और डेटा निर्यात (संकेतक)',
    about_title: 'परिचय',
    about_desc:
      'यह मंच नाभा के ग्रामीण क्षेत्रों में डिजिटल खाई को पाटने के लिए ऑफलाइन पाठ, बहुभाषी सामग्री और शिक्षक/प्रशासन टूल प्रदान करता है।',
  },
  pa: {
    appTitle: 'ਡਿਜਿਟਲ ਪਾਠਸ਼ਾਲਾ',
    welcome: 'ਡਿਜਿਟਲ ਪਾਠਸ਼ਾਲਾ ਵਿੱਚ ਸੁਆਗਤ ਹੈ',
    nav_home: 'ਮੁੱਖ',
    nav_about: 'ਬਾਰੇ',
    nav_student: 'ਵਿਦਿਆਰਥੀ',
    nav_teacher: 'ਅਧਿਆਪਕ',
    nav_admin: 'ਪ੍ਰਸ਼ਾਸਕ',
    nav_downloads: 'ਡਾਊਨਲੋਡ',
    nav_assignments: 'ਅਸਾਈਨਮੈਂਟ',
    nav_attendance: 'ਹਾਜ਼ਰੀ',
    nav_announcements: 'ਸੂਚਨਾਵਾਂ',
    nav_login: 'ਲੌਗਇਨ',
    nav_logout: 'ਲੌਗਆਊਟ',
    nav_dark: 'ਡਾਰਕ',
    nav_light: 'ਲਾਈਟ',
    home_problem: 'ਸਮੱਸਿਆ ਬਿਆਨ',
    home_expected: 'ਉਮੀਦਵਾਰ ਨਤੀਜੇ',
    home_point_offline: 'ਆਫਲਾਈਨ ਪਾਠ',
    home_point_locale: 'ਸਥਾਨਕ ਭਾਸ਼ਾ ਸਮੱਗਰੀ',
    home_point_dash: 'ਅਧਿਆਪਕ ਡੈਸ਼ਬੋਰਡ',
    student_title: 'ਵਿਦਿਆਰਥੀ ਡੈਸ਼ਬੋਰਡ',
    student_minutes: 'ਮਿੰਟ',
    student_download: 'ਡਾਊਨਲੋਡ',
    student_start: 'ਸ਼ੁਰੂ ਕਰੋ',
    student_status: 'ਸਥਿਤੀ',
    student_offline: 'ਆਫਲਾਈਨ',
    student_online: 'ਆਨਲਾਈਨ',
    student_progress: 'ਮੇਰੀ ਤਰੱਕੀ',
    teacher_title: 'ਅਧਿਆਪਕ ਡੈਸ਼ਬੋਰਡ',
    teacher_upload_label: 'ਸਰੋਤ ਅੱਪਲੋਡ ਕਰੋ',
    teacher_upload_btn: 'ਅੱਪਲੋਡ',
    admin_title: 'ਪ੍ਰਸ਼ਾਸਕ ਡੈਸ਼ਬੋਰਡ',
    admin_add_student: 'ਵਿਦਿਆਰਥੀ ਜੋੜੋ',
    admin_add_btn: 'ਜੋੜੋ',
    admin_manage: 'ਭੂਮਿਕਾਵਾਂ ਅਤੇ ਡਾਟਾ ਐਕਸਪੋਰਟ (ਸੰਕੇਤਕ)',
    about_title: 'ਬਾਰੇ',
    about_desc:
      'ਇਹ ਮੰਚ ਨਾਭਾ ਦੇ ਪਿੰਡਾਂ ਵਿੱਚ ਡਿਜਿਟਲ ਖਾਈ ਨੂੰ ਭਰਨ ਲਈ ਆਫਲਾਈਨ ਪਾਠ, ਬਹੁਭਾਸ਼ੀ ਸਮੱਗਰੀ ਅਤੇ ਅਧਿਆਪਕ/ਪ੍ਰਸ਼ਾਸਨ ਟੂਲ ਦਿੰਦਾ ਹੈ।',
  },
};
